STANDARD_BOARD = [
    {'name': 'Go', 'type': 'go', 'price': 0, 'rent': 0, 'color': 'none'},
    {'name': 'Mediterranean Avenue', 'type': 'real_estate', 'price': 60, 'rent': 2, 'color': 'brown'},
    {'name': 'Community Chest', 'type': 'community_chest', 'price': 0, 'rent': 0, 'color': 'none'},
    {'name': 'Baltic Avenue', 'type': 'real_estate', 'price': 60, 'rent': 4, 'color': 'brown'},
    {'name': 'Income Tax', 'type': 'tax', 'price': 0, 'rent': 0, 'color': 'none'},
    {'name': 'Reading Railroad', 'type': 'real_estate', 'price': 200, 'rent': 25, 'color': 'none'},
    {'name': 'Oriental Avenue', 'type': 'real_estate', 'price': 100, 'rent': 6, 'color': 'light_blue'},
    {'name': 'Chance', 'type': 'chance', 'price': 0, 'rent': 0, 'color': 'none'},
    {'name': 'Vermont Avenue', 'type': 'real_estate', 'price': 100, 'rent': 6, 'color': 'light_blue'},
    {'name': 'Connecticut Avenue', 'type': 'real_estate', 'price': 120, 'rent': 8, 'color': 'light_blue'},
    {'name': 'Jail', 'type': 'jail', 'price': 0, 'rent': 0, 'color': 'none'},
    {'name': 'St. Charles Place', 'type': 'real_estate', 'price': 140, 'rent': 10, 'color': 'pink'},
    {'name': 'Electric Company', 'type': 'real_estate', 'price': 150, 'rent': 4, 'color': 'none'},
    {'name': 'States Avenue', 'type': 'real_estate', 'price': 140, 'rent': 10, 'color': 'pink'},
    {'name': 'Virginia Avenue', 'type': 'real_estate', 'price': 160, 'rent': 12, 'color': 'pink'},
    {'name': 'Pennsylvania Railroad', 'type': 'real_estate', 'price': 200, 'rent': 25, 'color': 'none'},
    {'name': 'St. James Place', 'type': 'real_estate', 'price': 180, 'rent': 14, 'color': 'orange'},
    {'name': 'Community Chest', 'type': 'community_chest', 'price': 0, 'rent': 0, 'color': 'none'},
    {'name': 'Tennessee Avenue', 'type': 'real_estate', 'price': 180, 'rent': 14, 'color': 'orange'},
    {'name': 'New York Avenue', 'type': 'real_estate', 'price': 200, 'rent': 16, 'color': 'orange'},
    {'name': 'Free Parking', 'type': 'free_parking', 'price': 0, 'rent': 0, 'color': 'none'},
    {'name': 'Kentucky Avenue', 'type': 'real_estate', 'price': 220, 'rent': 18, 'color': 'red'},
    {'name': 'Chance', 'type': 'chance', 'price': 0, 'rent': 0, 'color': 'none'},
    {'name': 'Indiana Avenue', 'type': 'real_estate', 'price': 220, 'rent': 18, 'color': 'red'},
    {'name': 'Illinois Avenue', 'type': 'real_estate', 'price': 240, 'rent': 20, 'color': 'red'},
    {'name': 'B. & O. Railroad', 'type': 'real_estate', 'price': 200, 'rent': 25, 'color': 'none'},
    {'name': 'Atlantic Avenue', 'type': 'real_estate', 'price': 260, 'rent': 22, 'color': 'yellow'},
    {'name': 'Ventnor Avenue', 'type': 'real_estate', 'price': 260, 'rent': 22, 'color': 'yellow'},
    {'name': 'Water Works', 'type': 'real_estate', 'price': 150, 'rent': 4, 'color': 'none'},
    {'name': 'Marvin Gardens', 'type': 'real_estate', 'price': 280, 'rent': 24, 'color': 'yellow'},
    {'name': 'Go To Jail', 'type': 'go_to_jail', 'price': 0, 'rent': 0, 'color': 'none'},
    {'name': 'Pacific Avenue', 'type': 'real_estate', 'price': 300, 'rent': 26, 'color': 'green'},
    {'name': 'North Carolina Avenue', 'type': 'real_estate', 'price': 300, 'rent': 26, 'color': 'green'},
    {'name': 'Community Chest', 'type': 'community_chest', 'price': 0, 'rent': 0, 'color': 'none'},
    {'name': 'Pennsylvania Avenue', 'type': 'real_estate', 'price': 320, 'rent': 28, 'color': 'green'},
    {'name': 'Short Line', 'type': 'real_estate', 'price': 200, 'rent': 25, 'color': 'none'},
    {'name': 'Chance', 'type': 'chance', 'price': 0, 'rent': 0, 'color': 'none'},
    {'name': 'Park Place', 'type': 'real_estate', 'price': 350, 'rent': 35, 'color': 'blue'},
    {'name': 'Luxury Tax', 'type': 'tax', 'price': 0, 'rent': 0, 'color': 'none'},
    {'name': 'Boardwalk', 'type': 'real_estate', 'price': 400, 'rent': 50, 'color': 'blue'},
]
